.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH COLDECPLOT 1 "April 2020" Linux "User Commands"
.SH NAME
coldecplot \- displays collective decision and response history plots using options and data from a source file
.SH SYNOPSIS
.P
.B coldecplot [options] [file]
.SH DESCRIPTION
.P
.B coldecplot
stands for Collective Decision Plot.
.SH OPTIONS
.P
Mandatory arguments to long options are mandatory for short options too.
.TP
.BR \-h ", " \-\-help
display this help message
.TP
.BR \-r ", " \-\-realtime
read the data in real time
.TP
.BR \-t ", " \-\-top
force the window to stay on top
.SH KEYS
.TP
.BR L
show or hide the legend
.TP
.BR D
show or hide the decision data
.TP
.BR R
show or hide the response data
.TP
.BR C
clear the data and start reading the source file from the beginning again
.SH AUTHOR
Wout Provost