.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH COLDECPLOT 1 "April 2020" Linux "User Commands"
.SH NAME
coldecplot \- a graph plotter
.SH SYNOPSIS
.P
.B coldecplot [options] [file]
.SH DESCRIPTION
.P
Mandatory arguments to long options are mandatory for short options too.
.TP
.BR -h ", " --help
display this help message
.TP
.BR -r ", " --realtime
read the data in real time
.SH AUTHOR
Wout Provost