.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH COLDECSEED 1 "April 2020" Linux "User Commands"
.SH NAME
coldecseed \- generates one or more .argos files from a source .argos file, with each copy given a new random seed and new logfile name
.SH SYNOPSIS
.P
.B coldecseed [options] [file]
.SH DESCRIPTION
.P
Mandatory arguments to long options are mandatory for short options too.
.TP
.BR -h ", " --help
display this help message
.TP	
\fB\-m, \fB\-\-amount=\fINUM\fR	
the amount of files to generate
.SH AUTHOR
Wout Provost